name: DavidCopithorne
favicon: null
layout_spectrum: 0.74696
typography_spectrum: 0.37679
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cfdadc'
    - '#25282d'
    - '#44494d'
    - '#a0b3bc'
    - '#74664d'
  brandStrength: 0
  lightness: 0.8125
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
